import { renderToString } from 'react-dom/server';
import fs from 'fs';
import path from 'path';
import type { ViteDevServer } from 'vite';
import type { IStorage } from './storage';
import { markdownToHtml } from './markdown-to-html';
import { escapeHtml, escapeJson } from './html-escape';

/**
 * Server-side renderer for React app
 * Renders the React app to static HTML for crawlers
 */
export class SSRRenderer {
  private template: string | null = null;
  private vite: ViteDevServer | null = null;
  private storage: IStorage;
  
  constructor(storage: IStorage, vite?: ViteDevServer) {
    this.storage = storage;
    this.vite = vite || null;
  }
  
  /**
   * Render the React app to HTML string for the given URL
   */
  async renderPage(url: string): Promise<string> {
    try {
      if (this.vite) {
        return await this.renderWithVite(url);
      }
      return await this.renderProduction(url);
    } catch (error) {
      console.error('[SSR] Failed to render page:', error);
      return this.getFallbackHtml(url);
    }
  }
  
  private async renderWithVite(url: string): Promise<string> {
    return this.getFallbackHtml(url);
  }
  
  private async renderProduction(url: string): Promise<string> {
    return this.getFallbackHtml(url);
  }
  
  /**
   * Fallback HTML with actual page content for crawlers
   */
  private async getFallbackHtml(url: string): Promise<string> {
    const pathname = new URL(url, 'http://localhost').pathname;
    const baseUrl = 'https://aeostars.com';
    const canonicalUrl = `${baseUrl}${pathname === '/' ? '' : pathname}`;
    
    const pageTitle = this.getPageTitle(url);
    const pageDescription = this.getPageDescription(url);
    const pageKeywords = this.getPageKeywords(url);
    
    const pageContent = await this.getPageContent(pathname);
    const structuredData = await this.getStructuredData(pathname);
    
    const safeTitle = escapeHtml(pageTitle);
    const safeDescription = escapeHtml(pageDescription);
    const safeKeywords = escapeHtml(pageKeywords);
    
    return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
    <link rel="canonical" href="${canonicalUrl}" />
    <title>${safeTitle}</title>
    <meta name="description" content="${safeDescription}" />
    <meta name="keywords" content="${safeKeywords}" />
    <meta property="og:title" content="${safeTitle}" />
    <meta property="og:description" content="${safeDescription}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="${canonicalUrl}" />
    <meta property="og:site_name" content="AEOSTARS" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${safeTitle}" />
    <meta name="twitter:description" content="${safeDescription}" />
    ${structuredData}
  </head>
  <body>
    <div id="root">
      <header>
        <nav>
          <a href="/">Home</a>
          <a href="/news">News</a>
          <a href="/select-plan">Pricing</a>
        </nav>
      </header>
      <main>
        ${pageContent}
      </main>
      <footer>
        <p>&copy; 2026 AEOSTARS — AI Representation &amp; Visibility Intelligence</p>
      </footer>
    </div>
  </body>
</html>`;
  }
  
  /**
   * Get actual page content based on route
   */
  private async getPageContent(pathname: string): Promise<string> {
    if (pathname === '/') {
      return `
        <h1>AEOSTARS — AI Representation &amp; Visibility Intelligence Platform</h1>
        <p>AEOSTARS measures how your brand appears in answers generated by ChatGPT, Claude, and Gemini. Every day, our platform runs structured prompt batches across four intent types and three major LLMs, measuring whether your brand appears, at what position, and with what sentiment — then compares your results directly against your named competitors.</p>
        
        <h2>What is AI Representation &amp; Visibility Intelligence?</h2>
        <p>AI Representation &amp; Visibility Intelligence is the discipline of understanding and improving how large language models (LLMs) describe, recommend, and position your brand. As AI-generated answers replace traditional search results for a growing proportion of queries, the brands that appear in those answers capture disproportionate authority and commercial intent. AEOSTARS gives you the measurement layer to track, benchmark, and act on your AI presence.</p>

        <h2>Core Platform Features</h2>
        <ul>
          <li><strong>AI Visibility Dashboard:</strong> AI Share of Voice percentage, Commercial Recommendation Score, and Category Authority Score — updated daily with 30-day trend charts and a filterable results table by prompt type, model, and date range.</li>
          <li><strong>AI Perception Mirror:</strong> A structured narrative profile of how AI models describe your brand, including Positioning Clarity, Authority Depth, Proof Strength, and Differentiation Clarity scores (each 0–100), plus the top improvements most likely to increase your inclusion rate.</li>
          <li><strong>Competitor AI Positioning Map:</strong> Every prompt where a named competitor appeared in the LLM response but your brand did not — with the response snippet, competitor frequency, and an analysis of why they were recommended instead.</li>
          <li><strong>Semantic Coverage Gap Analysis:</strong> Topic clusters visualised by coverage strength (strong, weak, competitor-owned), with specific missing content types — commercial intent pages, FAQ structures, comparison pages — and recommended actions.</li>
          <li><strong>Machine Readability Audit:</strong> On-demand assessment of your site's LLM readability, checking Organisation schema, FAQ schema, Article schema, author markup, canonical tags, internal linking depth, and meta description quality — scored 0–100.</li>
          <li><strong>Change Monitoring &amp; Alerts:</strong> Daily automated comparison of today's AI responses against yesterday's — alerting you the moment a competitor gains ground, your brand disappears, or sentiment shifts across any model.</li>
          <li><strong>Report Exports:</strong> Executive Snapshot, Marketing Action Report, and Competitive Intelligence Report — each available as a structured PDF export.</li>
        </ul>

        <h2>How AI Share of Voice Is Calculated</h2>
        <p>AEOSTARS runs four prompt types against all three tracked LLMs (OpenAI ChatGPT, Anthropic Claude Haiku 4.5, Google Gemini 3.1 Pro): brand-direct queries, category comparison queries, commercial intent queries, and problem-based queries. AI Share of Voice is the percentage of total prompt runs in which your brand appeared in the response. We additionally calculate a Commercial Recommendation Score (inclusion rate on buying-intent prompts) and a Category Authority Score (inclusion rate on category comparison prompts) for a complete visibility picture.</p>

        <h2>Why AI Visibility Matters Now</h2>
        <p>AI-generated answers are now the primary interface between buyers and information across an increasing range of query types. When a potential customer asks an AI model which platform to use, which brand to trust, or which solution fits their problem, the models draw on their training data and retrieval sources to generate a recommendation. If your brand is not in that recommendation, you are invisible at the most authoritative moment in the buyer's journey. AEOSTARS is the measurement and intelligence platform that tells you where you stand, what your competitors are doing that you are not, and exactly what to address to improve your position.</p>

        <h2>Get Started</h2>
        <p>Connect your domain, name your competitors, define your category and core problem — AEOSTARS will run a full baseline AI visibility scan within minutes and have your dashboard populated with real data before you finish your first coffee.</p>
      `;
    }
    
    if (pathname === '/news') {
      try {
        const newsArticles = await this.storage.getAllNewsArticles(true);
        const articlesHtml = newsArticles
          .slice(0, 10)
          .map((article) => {
            const safeTitle = escapeHtml(article.title);
            const safeSlug = escapeHtml(article.slug);
            const safeDescription = escapeHtml(article.metaDescription);
            return `
            <article>
              <h2><a href="/news/${safeSlug}">${safeTitle}</a></h2>
              <p>${safeDescription}</p>
              <p><small>Published on ${new Date(article.publishedAt || '').toLocaleDateString()}</small></p>
            </article>
          `;
          }).join('\n');
        
        return `
          <h1>AI Visibility News &amp; Research</h1>
          <p>The latest research, strategies, and insights on AI brand representation, LLM visibility intelligence, and the evolving landscape of AI-generated answers.</p>
          ${articlesHtml}
        `;
      } catch (error) {
        console.error('[SSR] Failed to fetch news:', error);
        return `
          <h1>AI Visibility News &amp; Research</h1>
          <p>The latest insights on AI brand representation, visibility intelligence, and LLM monitoring strategies.</p>
        `;
      }
    }
    
    if (pathname.startsWith('/news/')) {
      const slug = pathname.split('/news/')[1];
      try {
        const allArticles = await this.storage.getAllNewsArticles(true);
        const article = allArticles.find(a => a.slug === slug);
        if (article) {
          const articleHtml = markdownToHtml(article.content || '');
          
          const jsonLd = {
            '@context': 'https://schema.org',
            '@type': 'Article',
            headline: escapeJson(article.title),
            description: escapeJson(article.metaDescription),
            keywords: article.keywords?.map(k => escapeJson(k)).join(', '),
            datePublished: article.publishedAt?.toISOString(),
            dateModified: article.updatedAt?.toISOString(),
            author: {
              '@type': 'Organization',
              name: 'AEOSTARS'
            },
            publisher: {
              '@type': 'Organization',
              name: 'AEOSTARS',
              url: 'https://aeostars.com'
            }
          };
          
          const safeTitle = escapeHtml(article.title);
          
          return `
            <script type="application/ld+json">
              ${JSON.stringify(jsonLd, null, 2)}
            </script>
            <article>
              <h1>${safeTitle}</h1>
              <p><small>Published on ${new Date(article.publishedAt || '').toLocaleDateString()}</small></p>
              <div>${articleHtml}</div>
            </article>
          `;
        }
      } catch (error) {
        console.error('[SSR] Failed to fetch article:', error);
      }
      
      return '<h1>Article Not Found</h1><p>The requested article could not be found.</p>';
    }
    
    if (pathname === '/pricing') {
      return `
        <h1>AEOSTARS Pricing — AI Brand Visibility Monitoring Plans</h1>
        <p>Transparent pricing for AI Representation &amp; Visibility Intelligence. Every plan includes daily automated scanning across OpenAI ChatGPT, Anthropic Claude Haiku 4.5, and Google Gemini 3.1, with no setup costs and no hidden fees.</p>
        
        <h2>Starter Plan — £29.99 per month</h2>
        <p>Ideal for in-house marketing teams and brands getting started with AI visibility monitoring. Billed annually.</p>
        <ul>
          <li>1 brand domain monitored</li>
          <li>3 competitor domains tracked</li>
          <li>Daily scanning across all three LLMs (ChatGPT, Claude Haiku 4.5, Gemini 3.1)</li>
          <li>AI Visibility Dashboard with Share of Voice scoring</li>
          <li>AI Perception Mirror — narrative profile with four scored dimensions</li>
          <li>Machine Readability Audit — on-demand, scored 0–100</li>
          <li>Change Monitoring &amp; Alerts — daily shift detection</li>
        </ul>
        
        <h2>Growth Plan — £79.99 per month (Most Popular)</h2>
        <p>For agencies and teams managing multiple brands or requiring the full competitive intelligence suite. Billed annually.</p>
        <ul>
          <li>Up to 5 brands monitored</li>
          <li>10 competitor domains tracked</li>
          <li>Daily scanning across all three LLMs</li>
          <li>Everything in Starter</li>
          <li>Competitor AI Positioning Map</li>
          <li>Semantic Coverage Gap Analysis</li>
          <li>PDF Report Exports — Executive, Marketing, and Competitive Intelligence</li>
        </ul>
        
        <h2>Enterprise Plan — Custom Pricing</h2>
        <p>For large brands, platforms, and high-volume operations requiring API access, white-label options, or dedicated support.</p>
        <ul>
          <li>Unlimited brands and custom scan frequency</li>
          <li>20+ competitor tracking</li>
          <li>Everything in Growth</li>
          <li>API access — integrate visibility data into your own stack</li>
          <li>White-label option</li>
          <li>Dedicated account manager</li>
          <li>Priority support</li>
        </ul>

        <h2>What Is Included in Every Plan</h2>
        <p>Every AEOSTARS plan includes the AI Visibility Dashboard, AI Perception Mirror, Machine Readability Audit, Change Monitoring &amp; Alerts, and onboarding scan. The Competitor AI Positioning Map, Semantic Coverage Gap Analysis, and PDF report exports are included from the Growth plan upward.</p>
      `;
    }
    
    return `
      <h1>${this.getPageTitle(`http://localhost${pathname}`)}</h1>
      <p>${this.getPageDescription(`http://localhost${pathname}`)}</p>
    `;
  }
  
  /**
   * Get page title based on URL (optimised for SEO — under 60 chars where possible)
   */
  private getPageTitle(url: string): string {
    const path = new URL(url, 'http://localhost').pathname;
    
    const titles: Record<string, string> = {
      '/': 'AEOSTARS — AI Representation & Visibility Intelligence',
      '/news': 'AI Visibility News & Research | AEOSTARS',
      '/pricing': 'Pricing — AI Brand Monitoring Plans | AEOSTARS',
      '/login': 'Sign In | AEOSTARS',
      '/signup': 'Register Interest | AEOSTARS',
      '/privacy': 'Privacy Policy | AEOSTARS',
      '/thank-you': 'Thank You | AEOSTARS',
    };
    
    return titles[path] || 'AEOSTARS — AI Representation & Visibility Intelligence';
  }
  
  /**
   * Get page description based on URL (optimised for SEO — under 160 chars)
   */
  private getPageDescription(url: string): string {
    const path = new URL(url, 'http://localhost').pathname;
    
    const descriptions: Record<string, string> = {
      '/': 'Track how your brand appears in ChatGPT, Claude, and Gemini answers. Measure AI Share of Voice, analyse your AI perception profile, and close competitive gaps across all major LLMs.',
      '/news': 'Research, strategies, and insights on AI brand representation, LLM visibility intelligence, and how brands are winning and losing in AI-generated answers.',
      '/pricing': 'AI brand visibility monitoring plans from £29.99/month. Daily scanning across ChatGPT, Claude Haiku 4.5, and Gemini 3.1. No setup fees. Cancel any time.',
      '/login': 'Sign in to your AEOSTARS dashboard and monitor your brand\'s AI visibility across ChatGPT, Claude, and Gemini.',
      '/signup': 'Register your interest in AEOSTARS — the AI Representation & Visibility Intelligence platform.',
      '/privacy': 'AEOSTARS privacy policy. How we collect, use, and protect your data in compliance with GDPR.',
      '/thank-you': 'Thank you for your interest in AEOSTARS.',
    };
    
    return descriptions[path] || 'AI Representation & Visibility Intelligence — measure and improve how your brand appears in AI-generated answers.';
  }

  /**
   * Get page keywords based on URL
   */
  private getPageKeywords(url: string): string {
    const path = new URL(url, 'http://localhost').pathname;
    
    const keywords: Record<string, string> = {
      '/': 'AI brand visibility, LLM brand monitoring, AI share of voice, ChatGPT brand tracking, Claude brand visibility, Gemini brand monitoring, AI representation intelligence, AEO platform, answer engine optimization',
      '/news': 'AI visibility news, LLM monitoring insights, AI brand representation research, AEO strategies, answer engine optimization updates',
      '/pricing': 'AEOSTARS pricing, AI brand monitoring plans, LLM visibility cost, AI share of voice platform, brand intelligence pricing',
      '/signup': 'AEOSTARS signup, AI visibility platform, register interest',
      '/privacy': 'privacy policy, data protection, GDPR, cookies',
    };
    
    return keywords[path] || 'AI brand visibility, LLM monitoring, AI representation intelligence, AEO';
  }

  /**
   * Get structured data (JSON-LD) for the page
   */
  private async getStructuredData(pathname: string): Promise<string> {
    const baseUrl = 'https://aeostars.com';
    const scripts: string[] = [];
    
    const organization = {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: 'AEOSTARS',
      url: baseUrl,
      logo: `${baseUrl}/aeostars-logo.png`,
      description: 'AI Representation & Visibility Intelligence platform — measure and improve how your brand appears in ChatGPT, Claude, and Gemini answers.',
      foundingDate: '2025',
      sameAs: [
        'https://www.linkedin.com/company/aeostars'
      ]
    };
    scripts.push(`<script type="application/ld+json">${JSON.stringify(organization)}</script>`);

    const website = {
      '@context': 'https://schema.org',
      '@type': 'WebSite',
      name: 'AEOSTARS',
      url: baseUrl,
      description: 'AI Representation & Visibility Intelligence — daily monitoring of how your brand appears in AI-generated answers.',
      potentialAction: {
        '@type': 'SearchAction',
        target: `${baseUrl}/news?q={search_term_string}`,
        'query-input': 'required name=search_term_string'
      }
    };
    scripts.push(`<script type="application/ld+json">${JSON.stringify(website)}</script>`);

    if (pathname === '/') {
      const software = {
        '@context': 'https://schema.org',
        '@type': 'SoftwareApplication',
        name: 'AEOSTARS',
        applicationCategory: 'BusinessApplication',
        operatingSystem: 'Web',
        description: 'AI Representation & Visibility Intelligence platform. Measure your brand\'s AI Share of Voice across ChatGPT, Claude Haiku 4.5, and Gemini 3.1 with daily automated scanning.',
        offers: {
          '@type': 'AggregateOffer',
          priceCurrency: 'GBP',
          lowPrice: '29.99',
          highPrice: '79.99',
          offerCount: 2,
          availability: 'https://schema.org/InStock'
        },
        featureList: [
          'AI Visibility Dashboard — daily Share of Voice scoring across ChatGPT, Claude Haiku 4.5, Gemini 3.1',
          'AI Perception Mirror — narrative profile with Positioning Clarity, Authority Depth, Proof Strength, and Differentiation Clarity scores',
          'Competitor AI Positioning Map — prompts where competitors appear and you do not',
          'Semantic Coverage Gap Analysis — topic cluster visualisation and content recommendations',
          'Machine Readability Audit — LLM readability score with schema and structure checks',
          'Change Monitoring & Alerts — daily shift detection across all three models',
          'Report Exports — Executive, Marketing, and Competitive Intelligence PDFs'
        ]
      };
      scripts.push(`<script type="application/ld+json">${JSON.stringify(software)}</script>`);

      const faq = {
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        mainEntity: [
          {
            '@type': 'Question',
            name: 'What is AI Representation & Visibility Intelligence?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'AI Representation & Visibility Intelligence is the practice of understanding and shaping how your brand is described, recommended, and positioned within large language model (LLM) responses from ChatGPT, Claude, and Gemini. AEOSTARS measures this automatically across four prompt types and three models, giving you a real, data-driven picture of your AI presence.'
            }
          },
          {
            '@type': 'Question',
            name: 'What is AI Share of Voice and how is it calculated?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'AI Share of Voice is the percentage of tracked prompt runs in which your brand appears in the LLM response. AEOSTARS runs four prompt types (brand-direct, category comparison, commercial intent, and problem-based) against three models (ChatGPT, Claude Haiku 4.5, Gemini 3.1). If your brand appears in 42 of 120 total prompt runs, your AI Share of Voice is 35%. We also calculate a Commercial Recommendation Score and Category Authority Score for granular insight.'
            }
          },
          {
            '@type': 'Question',
            name: 'Which AI models does AEOSTARS track?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'AEOSTARS currently tracks OpenAI ChatGPT, Anthropic Claude Haiku 4.5, and Google Gemini 3.1 Flash — the three models representing the dominant share of AI-generated answers in consumer and enterprise contexts.'
            }
          },
          {
            '@type': 'Question',
            name: 'How does the AI Perception Mirror work?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'The AI Perception Mirror interrogates each LLM directly — asking what it knows about your brand without feeding it your website — and analyses the response to build a structured profile. This profile includes Positioning Clarity, Authority Depth, Proof Strength, and Differentiation Clarity scores (each 0–100), plus specific improvements most likely to increase your inclusion rate.'
            }
          },
          {
            '@type': 'Question',
            name: 'How often does AEOSTARS scan the AI models?',
            acceptedAnswer: {
              '@type': 'Answer',
              text: 'AEOSTARS runs a full baseline scan when you first onboard, then performs daily automated visibility checks. The daily scheduler re-runs all prompt types, compares results to the previous day, and generates change alerts for significant shifts — including new competitor appearances, brand disappearances, and sentiment changes.'
            }
          }
        ]
      };
      scripts.push(`<script type="application/ld+json">${JSON.stringify(faq)}</script>`);
    }

    if (pathname === '/pricing') {
      const pricingProduct = {
        '@context': 'https://schema.org',
        '@type': 'Product',
        name: 'AEOSTARS AI Representation & Visibility Intelligence Platform',
        description: 'Measure and improve how your brand appears in AI-generated answers across ChatGPT, Claude, and Gemini.',
        brand: {
          '@type': 'Brand',
          name: 'AEOSTARS'
        },
        offers: [
          {
            '@type': 'Offer',
            name: 'Starter Plan',
            price: '29.99',
            priceCurrency: 'GBP',
            availability: 'https://schema.org/InStock',
            description: '1 brand, 3 competitors, daily scanning across all three LLMs — billed annually.'
          },
          {
            '@type': 'Offer',
            name: 'Growth Plan',
            price: '79.99',
            priceCurrency: 'GBP',
            availability: 'https://schema.org/InStock',
            description: 'Up to 5 brands, 10 competitors, full feature set including PDF reports — billed annually.'
          },
          {
            '@type': 'Offer',
            name: 'Enterprise Plan',
            priceCurrency: 'GBP',
            availability: 'https://schema.org/InStock',
            description: 'Unlimited brands, API access, white-label option, dedicated account manager — custom pricing.'
          }
        ]
      };
      scripts.push(`<script type="application/ld+json">${JSON.stringify(pricingProduct)}</script>`);
    }

    if (pathname === '/news') {
      try {
        const articles = await this.storage.getAllNewsArticles(true);
        const itemList = {
          '@context': 'https://schema.org',
          '@type': 'ItemList',
          name: 'AEOSTARS — AI Visibility News & Research',
          description: 'Research, strategies, and insights on AI brand representation and LLM visibility intelligence',
          numberOfItems: articles.length,
          itemListElement: articles.slice(0, 10).map((article, index) => ({
            '@type': 'ListItem',
            position: index + 1,
            url: `${baseUrl}/news/${article.slug}`,
            name: article.title
          }))
        };
        scripts.push(`<script type="application/ld+json">${JSON.stringify(itemList)}</script>`);
      } catch (error) {
        console.error('[SSR] Failed to generate news structured data:', error);
      }
    }

    return scripts.join('\n    ');
  }
}
